# Generated by Django 3.1 on 2020-08-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='b_roast',
            new_name='isBoast',
        ),
    ]
